version: "3.8"

services:
  postgres:
    image: postgres:latest
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - shorter-url

volumes:
  db:
    driver: local

networks:
  shorter-url:
    driver: bridge
