version: "3.8"
services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
      # Cria um segundo banco de dados para testes
      POSTGRES_MULTIPLE_DATABASES: "${DATABASE_NAME}_test"
    volumes:
      - db:/var/lib/postgresql/data
      # Script para criar múltiplos bancos de dados
      - ./init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh:ro
    networks:
      - shorter-url
  
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD:-}
    ports:
      - "6378:6379"
    volumes:
      - redis-data:/data
    networks:
      - shorter-url

volumes:
  db:
    driver: local
  redis-data:
    driver: local

networks:
  shorter-url:
    driver: bridge