version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - shorter-url

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD:-}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - shorter-url

volumes:
  db:
    driver: local
  redis-data:
    driver: local

networks:
  shorter-url:
    driver: bridge
