api:
  dashboard: true
  debug: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: shorter-url

# Configuração básica de logs
log:
  level: INFO

# Métricas (opcional)
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
