// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateShortUrl(ctx context.Context, arg CreateShortUrlParams) (uuid.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error)
	DeleteShortUrl(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetShortUrlById(ctx context.Context, id uuid.UUID) (ShortUrl, error)
	GetShortUrlBySlug(ctx context.Context, slug string) (ShortUrl, error)
	GetShortUrlsByUserId(ctx context.Context, userID uuid.UUID) ([]ShortUrl, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	IncrementAccessCount(ctx context.Context, arg IncrementAccessCountParams) error
	UpdateShortUrl(ctx context.Context, arg UpdateShortUrlParams) (uuid.UUID, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
