// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pgstore

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ShortUrl struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Slug        string
	OriginalUrl string
	CreatedAt   pgtype.Timestamp
	ExpiresAt   pgtype.Timestamp
	AccessCount pgtype.Int4
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	CreatedAt pgtype.Timestamp
}
